---
groups:
  nexus:
    platform: nxos
    username: cisco
    password: cisco
  ios:
    platform: ios
    username: cisco
    password: cisco
  huawei:
    platform: huawei
    username: 
    password: 
  junos:
    platform: junos
    username: 
    auth_private_key: ~/rocket/.ssh/xz
  ios-nfu:
    platform: ios
    username: cisco
    password: cisco
    
  core:
    role: core
  access:
    role: access

  su:
    site: su
  shab:
    site: shab

# filials


